version: '3'

services:
  postgres:
    image: postgres
    container_name : postgres_dev
    environment:
      - TZ=Europe/Paris
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DBNAME=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
      - "EXTRA_CONF=max_connections=300"
    ports:
      - 5432:5432
    # # To reactivate if you need data persistance
    # volumes:
    #   - "./data/postgres:/var/lib/postgresql/data"

  myticket:
    build:
      context: .
      dockerfile: build/Dockerfile
    container_name: myticket_dev
    env_file:
      - ./configs/.env
    ports:
      - 9098:9098
    volumes:
      - ./db:/app/db
